### ISSUE TITLE
CLI error

### ISSUE THREAD

**Issue by hibo-dtardia** [iconsauce/iconsauce#2]
When i try to use iconsauce from cli I have this error `sh: 1: iconsauce: not found`

To test I've made a simple project using code sample from docs 
- Installation https://github.com/iconsauce/docs/wiki#installation 
- CLI usage https://github.com/iconsauce/docs/wiki/CLI

**Desktop:**
 - OS: Ubuntu 20.04
 - Node v16.13.0
 - NPM v8.5.5 (it require Yarn?)

**Comment by hibo-dtardia** [comment]
I confirm that with Yarn all work. The problem is using it only with NPM

**Comment by vitto** [comment]
Do you have installed `iconsauce` globally or locally?

**Comment by hibo-dtardia** [comment]
> Do you have installed `iconsauce` globally or locally?

locally

**Comment by hibo-dtardia** [comment]
Unfortunately using `npx` give me another error `npm ERR! Cannot convert undefined or null to object`.
![Screenshot from 2022-05-09 15-49-48](https://user-images.githubusercontent.com/99898680/167425170-e7a5d49d-115f-4037-919e-512de25b6aae.png)

**Comment by vitto** [comment]
Ok, this is unexpected, thanks for the issue, we'll take a look as soon as we can.

**Comment by vitto** [comment]
We've found the problem:

```bash
npx @iconsauce/core --config iconsauce.config.js --output-css temp.css
```

With `npx` you have to run the package name instead of the bin name, so you should run `@iconsauce/core`. This isn't very elegant but it seems to solve your issue.

Let me know if it works.

**Comment by vitto** [comment]
I assume it worked since it works in my machine and after some test on other machines.
