### ISSUE TITLE
No icons found on Windows 10

### ISSUE THREAD

**Issue by vitto** [iconsauce/iconsauce#3]
**Describe the bug**

It seems iconsauce not finding icons on WIndows. It's probably related on how filesystem path works.

**To Reproduce**
This problem should run on every winows machine.

**Expected behavior**

My project has 60 icons but on windows it seems no icons are found.

**Screenshots**

![Screenshot_20220526_114419](https://user-images.githubusercontent.com/461484/170463430-4aa4a7c5-8059-45e5-9bee-35609e38ec8d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by nicolatamburini** [comment]
fix in commit 288264b
